#This playbook deploys to Jboss
- name: Deploy Jboss 7.1.1
  hosts: jboss
  become: yes
  tasks:

    - name: Remove EAR
      file:
        path:  /usr/share/jboss-as-7.1.1.Final/standalone/deployments/CiaoMondo.{{item}}
        state: absent
      loop:
        - ear
        - ear.failed

    - name: Remove CiaoMondo.ear.todeploy
      file:
        path:  /usr/share/jboss-as-7.1.1.Final/standalone/deployments/CiaoMondo.ear.deployed
        state: absent

    - name: Copy file
      copy:
        src: CiaoMondo.ear
        dest:  /usr/share/jboss-as-7.1.1.Final/standalone/deployments/
        owner: jboss
        group: jboss
        mode: 0755
        
    - name: Msg Failed
      wait_for:
        delay: 10
        path:  /usr/share/jboss-as-7.1.1.Final/standalone/deployments/CiaoMondo.ear.failed
        state: absent
        msg: Deploy OK
       
        
               
     
